### ISSUE TITLE
LuaRT-Studio x64 version crashes

### ISSUE THREAD

**Issue by c-sanchez** [samyeyo/LuaRT-Studio#17]
LuaRT-Studio x64 version crashes before startup.
Windows 7 x64.
![Lua-RT-Win7](https://i.ibb.co/s6mG5v3/luart-win7-x64.png)

**Comment by samyeyo** [comment]
Hi c-sanchez,

Thank you for the bug report.
What version of LuaRT Studio are you using the latest released on the LuaRT Studio repository (1.3.2) ?

Regards,

**Comment by c-sanchez** [comment]
Hi  @samyeyo, yes I tried with the current version 1.3.2, I also just tried with 1.3.1 and 1.2.0 both x64 versions and LuaRT-Studio does not start, it just shows the splash screen and crashes.

If you have a version with debug log  or if I can help in any other way let me know :)

**Comment by samyeyo** [comment]
Ok thank you for the precisions.
What is weird is that this error means that the executable has I think failed to load the `lua51.dll`
I have tested on a Windows 7 VM and LuaRT Studio started correctly
May be try without any antivirus?

**Comment by c-sanchez** [comment]
Well, I have nod32 antivirus and at no time has given me any alarm when downloading, extracting or running LuaRT-Studio, I have also disabled it to test and still the same error occurs.

The strange thing is that the x86 version does start without any problem.

**Comment by c-sanchez** [comment]
Hi @samyeyo, I just tried replacing lua54.dll using joedf's Lua builds (from lua-5.4.4_Win64_bin) and the x64 version of LuaRT-Studio started without problems.
https://github.com/joedf/LuaBuilds

Video of LuaRT-Studio x64 problem on Windows 7 and replacing lua54.dll
https://youtu.be/EREtqmdbbkU

I have no idea why it happens but I hope it helps to find the problem :)

**Comment by samyeyo** [comment]
Hi @c-sanchez !

Yes this test is valuable for me. It might be an initialization failure when loading lua54.dll
I have some checks to do, but I think I know what's causing this crash.
