### ISSUE TITLE
`arg[]` start at index 2 when using CMD paramaters in studio

### ISSUE THREAD

**Issue by pyroboots** [samyeyo/LuaRT-Studio#23]
When using command line arguments in Studio, it is set as the 2nd index instead of the first. The first index returns the filepath that the script is running from. This is annoying since the whole point of the command line params feature is to help you test, but instead you have to make a sort of offset. It works normally when running from a separate command prompt:
```
start echo.exe "hello!"
> hello!
```
I don't know if this is a debug feature but it just triggers me I guess.
```lua
print(arg[2]) -- prints the first arg
print(arg[1]) -- prints the filepath
```

Thanks for reading anyways! 👍

**Comment by samyeyo** [comment]
It's not LuaRT Studio related.

When running a LuaRT script, here is what the `arg` table contains : 

- `arg[2]` => command line argument at position 2 (ie the first argument provided for the script)
- `arg[1]` => command line argument at position 1 (ie the executing script path)
- `arg[0]` => The LuaRT interpreter

When running from a __compiled__ script, here is what the `arg` table contains :

- `arg[2]` => command line argument at position 2 (ie the second provided argument)
- `arg[1]` => command line argument at position 1 (ie the first provided argument)
- `arg[0]` => The running compiled script 

In standard Lua, the `arg` table contains :

- `arg[2]` => command line argument at position 2 after the script (ie the third provided argument)
- `arg[1]` => command line argument at position 1 after the script (ie the first provided argument)
- `arg[0]` => The executing script path
- `arg[-1]` => A Lua interpreter option 
- `arg[-2]` => A Lua interpreter option
- `arg[-3]` => A Lua interpreter option
- `arg[-4]` => The Lua interpreter

**Comment by pyroboots** [comment]
Oh, I didn't even know that `arg` existed in PUC-Lua!

**Comment by samyeyo** [comment]
In fact, there is no recommendation for the `arg` table, because it is created by the Lua interpreter and not the Lua runtime library.
For the next version of LuaRT, I will provide an implementation for the `arg` table closer to that of PUC Lua, for interpreted and compiled script (there won't be any differences anymore)
