### ISSUE TITLE
Left Panel background color cannot be changed

### ISSUE THREAD

**Issue by Gold-Vibes** [samyeyo/LuaRT-Studio#24]
Changing the style in both ZeroBrane Studio and LuaRT Studio works in ZeroBrane Studio in the left and right panels but doesn't correctly work in the left panel for LuaRT Studio. 

LuaRT Studio 1.6.0
ZeroBrane Studio 2.0.1
Windows 10 Pro 

The bundled version of LuaRT is also behind the current release version (1.6 vs 1.7) 

![2024-02-17 13_45_43-LuaRT Studio - C__Users_Atlantis_Downloads_App Portables_LuaRT-Studio-1 6 0-x64_](https://github.com/samyeyo/LuaRT-Studio/assets/13152544/dae51fe1-6a70-4d10-a130-f243a1bb8e8e)
![2024-02-17 13_47_23-2024-02-17 13_45_08-ZeroBrane Studio - C__Users_Atlantis_Downloads_App Portables](https://github.com/samyeyo/LuaRT-Studio/assets/13152544/986040a4-6b23-43bf-b8f5-f1991fdb3e29)

**Comment by samyeyo** [comment]
Thank you for the report.

> The bundled version of LuaRT is also behind the current release version (1.6 vs 1.7)

Yes didn't have time to update LuaRT Studio release packages 😞

**Comment by samyeyo** [comment]
I have it fixed internally, will be available with next LuaRT Studio release
